backend:
  name: git-gateway
  branch: main

media_folder: 'public/upload'
public_folder: '/upload'

collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Nextgen Hardware Solutions Blog' # Used in the UI
    folder: 'src/content/blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{day}}-{{month}}-{{year}}-{{slug}}' # Filename template, e.g., DD-MM-YYYY-title.md
    fields: # The fields for each document, usually in front matter
      # - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Publish Date', name: 'pubDate', widget: 'datetime' }
      - { label: 'Blog Entry Image', name: 'heroImage', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          hint: 'Add relevant tags for this post.',
        }
      - { 
          label: 'Language', 
          name: 'language', 
          widget: 'select', 
          options: 
            - { label: 'Polish', value: 'pl' }
            - { label: 'English', value: 'en' },
          default: 'pl',
          hint: 'Select the language of the post.'
        }  
